// Mock data for Inventory Management
export const mockInventory = [
  {
    _id: "inventory_001",
    propertyName: "Luxury Penthouse Suite",
    propertyType: "apartment",
    location: "Manhattan Heights, New York",
    price: 2500000,
    size: "2500 sq ft",
    bedrooms: 3,
    bathrooms: 3,
    status: "available",
    description: "Stunning penthouse with panoramic city views, private terrace, and premium finishes",
    features: ["City Views", "Private Terrace", "Premium Finishes", "Parking", "Concierge"],
    images: ["penthouse1.jpg", "penthouse2.jpg", "penthouse3.jpg"],
    listedDate: "2024-01-15T00:00:00Z",
    lastUpdated: "2024-01-24T14:30:00Z",
    agent: "John Smith",
    views: 45,
    inquiries: 8,
    notes: "High demand property, multiple showings scheduled"
  },
  {
    _id: "inventory_002",
    propertyName: "Modern Office Space",
    propertyType: "office",
    location: "Tech Plaza, San Francisco",
    price: 1200000,
    size: "5000 sq ft",
    bedrooms: 0,
    bathrooms: 2,
    status: "underContract",
    description: "Contemporary office space with open floor plan, perfect for tech startups",
    features: ["Open Floor Plan", "High-Speed Internet", "Parking", "Conference Rooms", "Kitchen"],
    images: ["office1.jpg", "office2.jpg"],
    listedDate: "2024-01-10T00:00:00Z",
    lastUpdated: "2024-01-22T11:20:00Z",
    agent: "Sarah Johnson",
    views: 32,
    inquiries: 5,
    notes: "Under contract, closing in 30 days"
  },
  {
    _id: "inventory_003",
    propertyName: "Family Villa with Pool",
    propertyType: "house",
    location: "Sunset Gardens, Miami",
    price: 850000,
    size: "3200 sq ft",
    bedrooms: 4,
    bathrooms: 3,
    status: "available",
    description: "Beautiful family home with private pool, garden, and modern amenities",
    features: ["Private Pool", "Garden", "Garage", "Modern Kitchen", "Master Suite"],
    images: ["villa1.jpg", "villa2.jpg", "villa3.jpg", "villa4.jpg"],
    listedDate: "2024-01-12T00:00:00Z",
    lastUpdated: "2024-01-19T13:30:00Z",
    agent: "Mike Wilson",
    views: 28,
    inquiries: 6,
    notes: "Perfect for families, pool maintenance included"
  },
  {
    _id: "inventory_004",
    propertyName: "Historic Townhouse",
    propertyType: "townhouse",
    location: "Heritage District, Boston",
    price: 950000,
    size: "2800 sq ft",
    bedrooms: 3,
    bathrooms: 2,
    status: "sold",
    description: "Charming historic townhouse with original features and modern updates",
    features: ["Historic Features", "Original Hardwood", "Fireplace", "Garden", "Parking"],
    images: ["townhouse1.jpg", "townhouse2.jpg"],
    listedDate: "2023-11-01T00:00:00Z",
    lastUpdated: "2023-12-15T16:55:00Z",
    agent: "Tom Davis",
    views: 67,
    inquiries: 12,
    notes: "Sold to preservation enthusiast, closed successfully"
  },
  {
    _id: "inventory_005",
    propertyName: "Downtown Retail Space",
    propertyType: "retail",
    location: "Downtown Plaza, Chicago",
    price: 650000,
    size: "2000 sq ft",
    bedrooms: 0,
    bathrooms: 1,
    status: "available",
    description: "Prime retail space in downtown area with high foot traffic",
    features: ["High Foot Traffic", "Street Frontage", "Storage", "Parking", "Flexible Layout"],
    images: ["retail1.jpg", "retail2.jpg"],
    listedDate: "2024-01-20T00:00:00Z",
    lastUpdated: "2024-01-25T08:45:00Z",
    agent: "Lisa Brown",
    views: 15,
    inquiries: 3,
    notes: "Great for restaurants or retail businesses"
  },
  {
    _id: "inventory_006",
    propertyName: "Skyline Condo with Views",
    propertyType: "condo",
    location: "Skyline Towers, Seattle",
    price: 1100000,
    size: "1800 sq ft",
    bedrooms: 2,
    bathrooms: 2,
    status: "pending",
    description: "Modern condo with breathtaking city and mountain views",
    features: ["City Views", "Mountain Views", "Balcony", "Gym Access", "Concierge"],
    images: ["condo1.jpg", "condo2.jpg", "condo3.jpg"],
    listedDate: "2024-01-18T00:00:00Z",
    lastUpdated: "2024-01-24T09:15:00Z",
    agent: "Jennifer Lee",
    views: 38,
    inquiries: 7,
    notes: "Pending offer, waiting for financing approval"
  },
  {
    _id: "inventory_007",
    propertyName: "Starter Home in Suburbs",
    propertyType: "house",
    location: "Sunrise Meadows, Austin",
    price: 450000,
    size: "2200 sq ft",
    bedrooms: 3,
    bathrooms: 2,
    status: "available",
    description: "Perfect starter home for young families in quiet neighborhood",
    features: ["Quiet Neighborhood", "Good Schools", "Garage", "Backyard", "Updated Kitchen"],
    images: ["starter1.jpg", "starter2.jpg"],
    listedDate: "2024-01-22T00:00:00Z",
    lastUpdated: "2024-01-24T10:30:00Z",
    agent: "Robert Taylor",
    views: 22,
    inquiries: 4,
    notes: "Great for first-time buyers, move-in ready"
  }
];

export const mockInventoryStats = {
  byStatus: [
    { name: "Available", count: 4 },
    { name: "Under Contract", count: 1 },
    { name: "Pending", count: 1 },
    { name: "Sold", count: 1 }
  ],
  byType: [
    { name: "House", count: 2 },
    { name: "Apartment", count: 1 },
    { name: "Condo", count: 1 },
    { name: "Office", count: 1 },
    { name: "Retail", count: 1 },
    { name: "Townhouse", count: 1 }
  ],
  byPriceRange: [
    { name: "Under $500K", count: 1 },
    { name: "$500K - $1M", count: 3 },
    { name: "$1M - $2M", count: 2 },
    { name: "Over $2M", count: 1 }
  ]
};
