// Mock data for Leads Management
export const mockLeads = [
  {
    _id: "lead_001",
    clientName: "Sarah Johnson",
    clientPhone: "1111111",
    clientEmail: "sarah@example.com",
    city: "New York",
    description: "Interested in luxury apartment in Manhattan",
    property: "Manhattan Heights",
    priority: "hot",
    status: "meetingDone",
    source: "instagram",
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-20T14:45:00Z",
    assignedTo: "John Smith",
    budget: 850000,
    notes: "Very interested, scheduled viewing for next week"
  },
  {
    _id: "lead_002",
    clientName: "Michael Chen",
    clientPhone: "1111111",
    clientEmail: "michael@example.com",
    city: "San Francisco",
    description: "Looking for tech-friendly office space",
    property: "Tech Plaza",
    priority: "veryHot",
    status: "contactedClientCall",
    source: "google",
    createdAt: "2024-01-18T09:15:00Z",
    updatedAt: "2024-01-22T11:20:00Z",
    assignedTo: "Sarah Johnson",
    budget: 1200000,
    notes: "High budget client, very responsive"
  },
  {
    _id: "lead_003",
    clientName: "Emily Rodriguez",
    clientPhone: "1111111",
    clientEmail: "emily@example.com",
    city: "Miami",
    description: "Family home with pool and garden",
    property: "Sunset Gardens",
    priority: "moderate",
    status: "followedUpCall",
    source: "facebook",
    createdAt: "2024-01-12T16:20:00Z",
    updatedAt: "2024-01-19T13:30:00Z",
    assignedTo: "Mike Wilson",
    budget: 650000,
    notes: "Prefers properties with outdoor space"
  },
  {
    _id: "lead_004",
    clientName: "David Thompson",
    clientPhone: "1111111",
    clientEmail: "david@example.com",
    city: "Chicago",
    description: "Commercial property for retail business",
    property: "Downtown Plaza",
    priority: "cold",
    status: "new",
    source: "referral",
    createdAt: "2024-01-25T08:45:00Z",
    updatedAt: "2024-01-25T08:45:00Z",
    assignedTo: "Lisa Brown",
    budget: 950000,
    notes: "Referred by existing client, needs follow-up"
  },
  {
    _id: "lead_005",
    clientName: "Anna Kowalski",
    clientPhone: "1111111",
    clientEmail: "anna@example.com",
    city: "Boston",
    description: "Historic townhouse renovation project",
    property: "Heritage District",
    priority: "veryCold",
    status: "closedLost",
    source: "directCall",
    createdAt: "2024-01-08T14:10:00Z",
    updatedAt: "2024-01-23T16:55:00Z",
    assignedTo: "Tom Davis",
    budget: 750000,
    notes: "Budget constraints, decided to wait"
  },
  {
    _id: "lead_006",
    clientName: "James Wilson",
    clientPhone: "1111111",
    clientEmail: "james@example.com",
    city: "Seattle",
    description: "Modern condo with city views",
    property: "Skyline Towers",
    priority: "hot",
    status: "meetingAttempt",
    source: "facebookComment",
    createdAt: "2024-01-20T11:30:00Z",
    updatedAt: "2024-01-24T09:15:00Z",
    assignedTo: "Jennifer Lee",
    budget: 1100000,
    notes: "Scheduled meeting, client rescheduled twice"
  },
  {
    _id: "lead_007",
    clientName: "Maria Garcia",
    clientPhone: "1111111",
    clientEmail: "maria@example.com",
    city: "Austin",
    description: "Starter home for young family",
    property: "Sunrise Meadows",
    priority: "moderate",
    status: "contactedClientEmail",
    source: "friendAndFamily",
    createdAt: "2024-01-22T15:45:00Z",
    updatedAt: "2024-01-24T10:30:00Z",
    assignedTo: "Robert Taylor",
    budget: 450000,
    notes: "First-time buyers, need guidance on process"
  }
];

export const mockLeadStats = {
  status: [
    { name: "New", count: 1 },
    { name: "Contacted", count: 2 },
    { name: "Meeting Scheduled", count: 1 },
    { name: "Closed Won", count: 1 },
    { name: "Closed Lost", count: 1 },
    { name: "Follow-up", count: 1 }
  ],
  priority: [
    { name: "Very Hot", count: 1 },
    { name: "Hot", count: 2 },
    { name: "Moderate", count: 2 },
    { name: "Cold", count: 1 },
    { name: "Very Cold", count: 1 }
  ],
  source: [
    { name: "Instagram", count: 1 },
    { name: "Google", count: 1 },
    { name: "Facebook", count: 1 },
    { name: "Referral", count: 1 },
    { name: "Direct Call", count: 1 },
    { name: "Family", count: 1 },
    { name: "Facebook Comment", count: 1 }
  ]
};
