// Mock data for Societies Management
export const mockSocieties = [
  {
    _id: "society_001",
    name: "A Heights Residency",
    location: "Upper East Side, New York",
    type: "residential",
    totalUnits: 150,
    availableUnits: 12,
    priceRange: "2M - 5M",
    amenities: ["Swimming Pool", "Gym", "Concierge", "Parking", "Rooftop Garden"],
    developer: "A Properties LLC",
    completionDate: "2024-12-31T23:59:59Z",
    status: "underConstruction",
    description: "Luxury residential complex with world-class amenities",
    contactPerson: "John Smith",
    phone: "1111111",
    email: "contact@example.com",
    website: "www.manhattanheights.com",
    createdAt: "2023-12-15T10:00:00Z",
    updatedAt: "2024-01-24T14:30:00Z",
    notes: "Phase 1 completed, Phase 2 in progress"
  },
  {
    _id: "society_002",
    name: "B Plaza Business Center",
    location: "SOMA District, San Francisco",
    type: "commercial",
    totalUnits: 25,
    availableUnits: 3,
    priceRange: "1M - 3M",
    amenities: ["High-Speed Internet", "Conference Rooms", "Parking", "Cafeteria", "Security"],
    developer: "B Industries",
    completionDate: "2025-06-30T23:59:59Z",
    status: "planning",
    description: "Modern office complex designed for tech companies",
    contactPerson: "Sarah Johnson",
    phone: "1111111",
    email: "contact@example.com",
    website: "www.techplaza.com",
    createdAt: "2024-01-10T09:15:00Z",
    updatedAt: "2024-01-22T11:20:00Z",
    notes: "Pre-leasing available, permits pending"
  },
  {
    _id: "society_003",
    name: "C Gardens Community",
    location: "Coral Gables, Miami",
    type: "residential",
    totalUnits: 200,
    availableUnits: 45,
    priceRange: "800K - 1.5M",
    amenities: ["Swimming Pool", "Tennis Courts", "Clubhouse", "Gym", "Playground"],
    developer: "C Development Group",
    completionDate: "2024-08-31T23:59:59Z",
    status: "underConstruction",
    description: "Family-friendly residential community with resort-style amenities",
    contactPerson: "Mike Wilson",
    phone: "1111111",
    email: "contact@example.com",
    website: "www.sunsetgardens.com",
    createdAt: "2023-10-15T14:20:00Z",
    updatedAt: "2024-01-19T13:30:00Z",
    notes: "Phase 2 construction in progress, Phase 1 sold out"
  },
  {
    _id: "society_004",
    name: "D District Restoration",
    location: "Beacon Hill, Boston",
    type: "mixed",
    totalUnits: 50,
    availableUnits: 0,
    priceRange: "900K - 2M",
    amenities: ["Historic Features", "Garden", "Parking", "Security", "Maintenance"],
    developer: "D Preservation Society",
    completionDate: "2023-12-15T23:59:59Z",
    status: "completed",
    description: "Historic townhouse restoration with modern amenities",
    contactPerson: "Tom Davis",
    phone: "1111111",
    email: "contact@example.com",
    website: "www.heritagedistrict.com",
    createdAt: "2023-05-20T16:10:00Z",
    updatedAt: "2023-12-15T16:55:00Z",
    notes: "All units sold, project completed successfully"
  },
  {
    _id: "society_005",
    name: "E Towers Complex",
    location: "Belltown, Seattle",
    type: "residential",
    totalUnits: 300,
    availableUnits: 75,
    priceRange: "1.1M - 2.5M",
    amenities: ["City Views", "Gym", "Concierge", "Parking", "Rooftop Deck"],
    developer: "E Development Corp",
    completionDate: "2025-12-31T23:59:59Z",
    status: "underConstruction",
    description: "High-rise residential tower with panoramic city views",
    contactPerson: "Jennifer Lee",
    phone: "1111111",
    email: "contact@example.com",
    website: "www.skylinetowers.com",
    createdAt: "2023-12-01T11:30:00Z",
    updatedAt: "2024-01-24T09:15:00Z",
    notes: "Foundation completed, frame construction in progress"
  },
  {
    _id: "society_006",
    name: "F Meadows Subdivision",
    location: "Round Rock, Austin",
    type: "residential",
    totalUnits: 100,
    availableUnits: 100,
    priceRange: "400K - 600K",
    amenities: ["Community Pool", "Playground", "Walking Trails", "Clubhouse", "Parking"],
    developer: "F Development Partners",
    completionDate: "2025-10-31T23:59:59Z",
    status: "planning",
    description: "New residential subdivision for young families",
    contactPerson: "Robert Taylor",
    phone: "1111111",
    email: "contact@example.com",
    website: "www.sunrisemeadows.com",
    createdAt: "2024-01-15T15:45:00Z",
    updatedAt: "2024-01-24T10:30:00Z",
    notes: "Pre-construction sales, groundbreaking in April"
  },
  {
    _id: "society_007",
    name: "G Plaza Commercial",
    location: "Loop District, Chicago",
    type: "commercial",
    totalUnits: 40,
    availableUnits: 8,
    priceRange: "800K - 2M",
    amenities: ["High Foot Traffic", "Parking", "Security", "Flexible Layout", "Storage"],
    developer: "G Business Association",
    completionDate: "2024-11-30T23:59:59Z",
    status: "onHold",
    description: "Prime commercial space in downtown business district",
    contactPerson: "Lisa Brown",
    phone: "1111111",
    email: "contact@example.com",
    website: "www.downtownplaza.com",
    createdAt: "2024-01-20T08:45:00Z",
    updatedAt: "2024-01-25T08:45:00Z",
    notes: "Project on hold due to funding issues, some units available"
  }
];

export const mockSocietyStats = {
  byStatus: [
    { name: "Under Construction", count: 3 },
    { name: "Planning", count: 2 },
    { name: "Completed", count: 1 },
    { name: "On Hold", count: 1 }
  ],
  byType: [
    { name: "Residential", count: 4 },
    { name: "Commercial", count: 2 },
    { name: "Mixed", count: 1 }
  ],
  byDeveloper: [
    { name: "Manhattan Properties", count: 1 },
    { name: "TechCorp Industries", count: 1 },
    { name: "Sunset Development", count: 1 },
    { name: "Heritage Preservation", count: 1 },
    { name: "Skyline Development", count: 1 },
    { name: "Sunrise Partners", count: 1 },
    { name: "Downtown Association", count: 1 }
  ]
};
